when:
  - event: push
    branch:
      - main
      - develop

depends_on:
  - validate-backend

steps:
  - name: Generate and Upload Coverage
    image: xd009642/tarpaulin:latest
    commands:
      - cargo tarpaulin --engine llvm --skip-clean --coveralls "$COVERALLS_TOKEN"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      COVERALLS_TOKEN:
        from_secret: coveralls_token
