when:
  - event: push
  - event: pull_request

steps:
  # DOCKER
  - name: "[Docker] Build Test Image"
    image: docker
    commands:
      - docker build -t local/tarpaulin-with-chromedriver .woodpecker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  - name: "[Backend] Test"
    depends_on: [ "[Docker] Build Test Image" ]
    image: local/tarpaulin-with-chromedriver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - RUST_BACKTRACE=full CHROMEDRIVER_NO_SANDBOX=true cargo test
    environment:
      COVERALLS_TOKEN:
        from_secret: coveralls_token
